# Generated by Django 5.0.8 on 2024-09-28 21:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الـفرع')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الوظيفه')),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='حالة الضابط')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الرتبه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ranks/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الــوحدة')),
            ],
        ),
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=' حالة الضابط بالوحدة')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الســلاح')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='قائد الفرع')),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم الضابط')),
                ('military_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم العسكري')),
                ('seniority_number', models.CharField(max_length=50, verbose_name='رقم الاقدمية')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='الرقم القومي')),
                ('phone1', models.CharField(max_length=15, verbose_name='رقم الهاتف ١')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف ٢')),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم هاتف المنزل')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='officers/', verbose_name='الصورة الشخصية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانضمام')),
                ('batch_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='رقم الدفعة')),
                ('rank_promotion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر ترقي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.bloodtype', verbose_name='فصيلة الدم')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_officers', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.job', verbose_name='الوظيفه')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.maritalstatus', verbose_name='الحالة الإجتماعية')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_officers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.officerstatus', verbose_name='الحالة')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.rank', verbose_name='الرتبة')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'سنوية'), ('casual', 'عارضة'), ('leader_grant', 'منحة قائد'), ('instead_of_rest', 'بدل راحة')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'جـاري التصديــق'), ('approved', 'تصــدق '), ('rejected', 'مرفــوض')], default='pending', max_length=200, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المصدق الحالي')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_request', to=settings.AUTH_USER_MODEL)),
                ('final_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approver', to=settings.AUTH_USER_MODEL, verbose_name='المصدق النهائي')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='officers_affairs.officer', verbose_name='الضابط')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الـقسم')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='officers_affairs.branch', verbose_name='الـفرع')),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.section', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='job',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='officers_affairs.section', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='officer',
            name='previous_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_units', to='officers_affairs.unit', verbose_name='الوحدة السابقة'),
        ),
        migrations.AddField(
            model_name='officer',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_unit', to='officers_affairs.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='officer',
            name='unit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.unitstatus', verbose_name='الحالة بالوحدة'),
        ),
        migrations.AddField(
            model_name='officer',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.weapon', verbose_name='السلاح'),
        ),
    ]
