# Generated by Django 5.0.8 on 2024-09-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأيام المأخوذة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ انتهاء الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ بداية الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'جـاري التصديــق'), ('approved', 'تصــدق'), ('rejected', 'لم يتصدق')], default='pending', max_length=200, verbose_name='الحالة'),
        ),
    ]
