# Generated by Django 5.0.8 on 2024-09-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='batch_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='رقم الدفعة'),
        ),
    ]
