# Generated by Django 5.0.8 on 2024-08-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.CharField(choices=[('active', 'خدمة'), ('retired', 'معاش')], max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='unit_status',
            field=models.CharField(choices=[('current', 'موجود'), ('transferred', 'منقول'), ('mission', 'مأمورية')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('lieutenant', 'ملازم'), ('first_lieutenant', 'ملازم أول'), ('captain', 'نقيب'), ('major', 'رائد'), ('lieutenant_colonel', 'مقدم'), ('colonel', 'عقيد'), ('Brigadier_General', 'عميد')], max_length=100, unique=True),
        ),
    ]
