# Generated by Django 5.0.8 on 2024-08-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0002_alter_officer_status_alter_officer_unit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.CharField(choices=[('خدمة', 'خدمة'), ('معاش', 'معاش')], max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='unit_status',
            field=models.CharField(choices=[('موجود', 'موجود'), ('منقول', 'منقول'), ('مأمورية', 'مأمورية')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('ملازم', 'ملازم'), ('ملازم أول', 'ملازم أول'), ('نقيب', 'نقيب'), ('رائد', 'رائد'), ('مقدم', 'مقدم'), ('عقيد', 'عقيد'), ('عميد', 'عميد')], max_length=100, unique=True),
        ),
    ]
