# Generated by Django 5.0.8 on 2024-09-18 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0002_alter_officer_batch_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='قائد الفرع'),
        ),
        migrations.AddField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ranks/', verbose_name='صورة الرتبه'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='الرتبه'),
        ),
    ]
