# Generated by Django 5.0.8 on 2024-08-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0003_alter_officer_status_alter_officer_unit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='promotion_date',
        ),
    ]
