# Generated by Django 5.0.8 on 2024-08-31 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0004_remove_officer_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
