# Generated by Django 5.0.8 on 2024-10-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0004_leaverequest_remaining_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'سنوية'), ('casual', 'عارضة'), ('leader_grant', 'منحة قائد'), ('instead_of_rest', 'بدل راحة'), ('rest', ' راحة')], max_length=20, verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأيام المتبقية'),
        ),
    ]
