# Generated by Django 5.0.8 on 2024-08-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0005_alter_officer_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.CharField(choices=[('serv', 'خدمة'), ('معاش', 'معاش')], default='serv', max_length=20),
        ),
    ]
