# Generated by Django 5.0.8 on 2024-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0006_alter_officer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.IntegerField(choices=[(1, 'خدمة'), (0, 'معاش')], default=1),
        ),
    ]
