# Generated by Django 5.0.8 on 2024-10-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('officers_affairs', '0007_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='الفرع'),
        ),
    ]
