# Generated by Django 5.0.8 on 2024-09-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0007_alter_officer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_status', models.IntegerField(choices=[(1, 'موجود'), (2, 'مأمورية'), (0, 'منقول')])),
            ],
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('7', 'ملازم'), ('6', 'ملازم أول'), ('5', 'نقيب'), ('4', 'رائد'), ('3', 'مقدم'), ('2', 'عقيد'), ('1', 'عميد')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='unit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.unitstatus'),
        ),
    ]
