# Generated by Django 5.0.8 on 2024-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0008_unitstatus_alter_rank_name_alter_officer_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='اسم الذابط'),
        ),
    ]
