# Generated by Django 5.0.8 on 2024-09-03 12:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0009_alter_officer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='batch_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='رقم الدفعة'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='blood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.bloodtype', verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='full_name',
            field=models.CharField(error_messages={'required': 'DRY ...'}, max_length=255, verbose_name='اسم الضابط'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم هاتف المنزل'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.job', verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='military_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرقم العسكري'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='phone1',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف 1'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف 2'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='previous_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_units', to='officers_affairs.unit', verbose_name='الوحدة السابقة'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='officers/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.rank', verbose_name='الرتبة'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank_promotion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر ترقي'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.section', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='seniority_number',
            field=models.CharField(max_length=50, verbose_name='رقم الاقدمية'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.IntegerField(choices=[(1, 'خدمة'), (0, 'معاش')], default=1, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_unit', to='officers_affairs.unit', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='unit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.unitstatus', verbose_name='الحالة بالوحدة'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.weapon', verbose_name='السلاح'),
        ),
    ]
