# Generated by Django 5.0.8 on 2024-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0010_alter_officer_address_alter_officer_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='اسم الضابط'),
        ),
    ]
