# Generated by Django 5.0.8 on 2024-10-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0011_alter_officer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ')),
                ('status', models.CharField(choices=[('present', 'موجود'), ('mission', 'مامورية'), ('open_mission', 'مأمورية مفتوحه من - إلي'), ('hospital', 'مستشفي'), ('leave', 'إجازة'), ('travel', 'سفر بالخارج'), ('permission', 'إذن')], max_length=20, verbose_name='الحالة')),
                ('leave_type', models.CharField(blank=True, choices=[('annual', 'سنوية'), ('casual', 'عارضة'), ('instead_of_rest', 'بدل راحة'), ('leader_grant', 'منحة قائد'), ('rest', 'راحة')], max_length=20, null=True, verbose_name='نوع الإجازة')),
                ('mission_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل المأمورية')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers_affairs.officer', verbose_name='الضابط')),
            ],
            options={
                'verbose_name': 'تمام يومي',
                'verbose_name_plural': 'تمامات يومية',
                'unique_together': {('officer', 'date')},
            },
        ),
    ]
