# Generated by Django 5.0.8 on 2024-09-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0011_alter_officer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('م', 'ملازم'), ('نق', 'نقيب')], max_length=100, unique=True),
        ),
    ]
