# Generated by Django 5.0.8 on 2024-10-05 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0012_dailyattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='mission_details',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.unitstatus', verbose_name='الحالة اليومية'),
        ),
    ]
