# Generated by Django 5.0.8 on 2024-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0012_alter_rank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('ملازم', 'ملازم'), ('ملازم اول', 'ملازم أول'), ('نقيب', 'نقيب'), ('رائد', 'رائد'), ('مقدم', 'مقدم'), ('عقيد', 'عقيد'), ('عميد', 'عميد')], max_length=100, unique=True),
        ),
    ]
