# Generated by Django 5.0.8 on 2024-10-05 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0013_remove_dailyattendance_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='previous_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.dailyattendance'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
    ]
