# Generated by Django 5.0.8 on 2024-09-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0014_alter_rank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('7', 'ملازم'), ('6', 'ملازم أول'), ('5', 'نقيب'), ('4', 'رائد'), ('3', 'مقدم'), ('2', 'عقيد'), ('1', 'عميد')], max_length=100, unique=True),
        ),
    ]
