# Generated by Django 5.0.8 on 2024-10-05 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0014_dailyattendance_previous_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='previous_attendance',
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
    ]
