# Generated by Django 5.0.8 on 2024-10-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0015_remove_dailyattendance_previous_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='compensation_date',
            field=models.DateField(blank=True, null=True, verbose_name='بدل عن ترايخ'),
        ),
    ]
