# Generated by Django 5.0.8 on 2024-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0016_leaverequest_compensation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='compensation_date',
            field=models.DateField(null=True, verbose_name='بدل عن ترايخ'),
        ),
    ]
