# Generated by Django 5.0.8 on 2024-10-18 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0019_shift_shiftswaprequest_shiftteam_shift_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='new_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_shift', to='officers_affairs.shift', verbose_name='النوبطچية الجديدة'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='original_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_shift', to='officers_affairs.shift', verbose_name='النوبطچية الأصلية'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='requesting_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='officers_affairs.officer', verbose_name='الضابط المقدم للطلب'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='target_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_targets', to='officers_affairs.officer', verbose_name='الضابط المستهدف'),
        ),
        migrations.AlterField(
            model_name='shiftteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='shiftteam',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_teams', to='officers_affairs.officer', verbose_name='الضابط'),
        ),
        migrations.AlterField(
            model_name='shiftteam',
            name='team_type',
            field=models.CharField(choices=[('قائد منوب', 'قائد منوب'), ('ضابط نوبطچي', 'ضابط نوبطچي')], max_length=20, verbose_name='نوع الطاقم'),
        ),
        migrations.CreateModel(
            name='MorningParadeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers_affairs.officer', verbose_name='الضابط')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers_affairs.unitstatus', verbose_name='حالة الحضور')),
            ],
            options={
                'verbose_name': 'حضور الطابور الصباحي',
                'verbose_name_plural': 'حضور الطابور الصباحي',
                'unique_together': {('officer', 'date')},
            },
        ),
    ]
