# Generated by Django 5.0.8 on 2024-10-18 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0020_alter_shiftswaprequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningparadeattendance',
            name='status',
            field=models.CharField(choices=[('حضر', 'حضر'), ('لم يحضر', 'لم يحضر')], default=1, max_length=10, verbose_name='حالة الحضور'),
            preserve_default=False,
        ),
    ]
