# Generated by Django 5.0.8 on 2024-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0021_alter_morningparadeattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningparadeattendance',
            name='status',
            field=models.CharField(choices=[('حضر', 'حضر'), ('لم يحضر', 'لم يحضر')], max_length=20, verbose_name='حالة الحضور'),
        ),
    ]
