# Generated by Django 5.0.8 on 2024-10-19 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0022_alter_morningparadeattendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftswaprequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموافق الحالي'),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='final_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShiftSwapRequest', to=settings.AUTH_USER_MODEL, verbose_name='الموافق النهائي'),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'جاري الموافقة'), ('approved', 'موافق'), ('rejected', 'لم يوافق')], default='pending', max_length=200, verbose_name='الحالة'),
        ),
    ]
