# Generated by Django 5.0.8 on 2024-10-19 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0024_alter_shiftswaprequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المصدق الحالي'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='final_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShiftSwapRequest', to=settings.AUTH_USER_MODEL, verbose_name='المصدق النهائي'),
        ),
    ]
