# Generated by Django 5.0.8 on 2024-10-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0025_alter_shiftswaprequest_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الضم'),
        ),
    ]
