# Generated by Django 5.0.8 on 2024-10-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0026_alter_officer_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_type', models.CharField(choices=[('مدني', 'مدني'), ('عسكري', 'عسكري')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('visit_reason', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerGateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers_affairs.officer')),
            ],
        ),
    ]
