# Generated by Django 5.0.8 on 2024-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0027_visitorlog_officergatelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officergatelog',
            name='status',
        ),
        migrations.AddField(
            model_name='officergatelog',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
