# Generated by Django 5.0.8 on 2024-11-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers_affairs', '0028_remove_officergatelog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
